#!/usr/bin/env python3
# Generates adapters/c/src/nfc_tables.c (+ relies on the hand-written
# adapters/c/src/nfc_tables.h for the struct/extern declarations): canonical
# decomposition, combining-class, and canonical-composition data tables for
# a from-scratch C NFC (Unicode Normalization Form C) implementation.
#
# Why this exists: C has no stdlib Unicode normalization API at all (unlike
# Python's unicodedata, Java's java.text.Normalizer, JS's
# String.prototype.normalize, or Rust's unicode-normalization crate used
# elsewhere in this project), and pulling in a third-party library was ruled
# out per CONTRIBUTING.md's stdlib-only adapter convention. Ground truth for
# every table entry is Python's own unicodedata module (stdlib), the same
# source the Go adapter's equivalent generator
# (adapters/go/scripts/gen_nfc_tables.py) uses, so results are
# cross-checked against a working sibling implementation.
#
# Hangul syllables (and Hangul Jamo L/V/T composition) are excluded from the
# generated tables and handled algorithmically in nfc.c instead (the
# standard arithmetic Hangul decomposition/composition rule), matching the
# Go adapter and every other reference NFC implementation, to avoid an
# ~11172-entry Hangul table.
#
# Tables are emitted sorted by codepoint (decomp/combining) or by
# (cp1, cp2) (compose) so nfc.c can binary-search them.
#
# Run: python3 adapters/c/scripts/gen_nfc_tables.py > adapters/c/src/nfc_tables.c

import unicodedata
import sys

SBase, LBase, VBase, TBase = 0xAC00, 0x1100, 0x1161, 0x11A7
LCount, VCount, TCount = 19, 21, 28
NCount = VCount * TCount
SCount = LCount * NCount


def is_hangul_syllable(cp):
    return SBase <= cp < SBase + SCount


decomp = {}       # cp -> full NFD decomposition, list[int], non-Hangul
combining = {}     # cp -> combining class, only nonzero
compose_pairs = {}  # (cp1, cp2) -> composed cp, verified against Python's NFC

MAX_CP = 0x110000

for cp in range(MAX_CP):
    if is_hangul_syllable(cp):
        continue
    ch = chr(cp)
    ccc = unicodedata.combining(ch)
    if ccc != 0:
        combining[cp] = ccc
    nfd = unicodedata.normalize('NFD', ch)
    if nfd != ch:
        decomp[cp] = [ord(c) for c in nfd]

    raw = unicodedata.decomposition(ch)
    if not raw or raw.startswith('<'):
        continue
    parts = [int(x, 16) for x in raw.split(' ')]
    if len(parts) != 2:
        continue
    cp1, cp2 = parts
    if is_hangul_syllable(cp1) or is_hangul_syllable(cp2):
        continue
    if unicodedata.combining(chr(cp1)) != 0:
        continue
    test = unicodedata.normalize('NFC', chr(cp1) + chr(cp2))
    if len(test) == 1 and ord(test[0]) == cp:
        compose_pairs[(cp1, cp2)] = cp

out = []
out.append("// Code generated by adapters/c/scripts/gen_nfc_tables.py; DO NOT EDIT.")
out.append("// Ground truth: Python stdlib unicodedata, Unicode %s." % unicodedata.unidata_version)
out.append('#include "nfc_tables.h"')
out.append("")

pool = []
decomp_entries = []
for cp in sorted(decomp):
    seq = decomp[cp]
    decomp_entries.append((cp, len(pool), len(seq)))
    pool.extend(seq)

out.append("const uint32_t nfc_decomp_pool[] = {")
for i in range(0, len(pool), 12):
    out.append("    " + ", ".join("0x%x" % v for v in pool[i:i + 12]) + ",")
out.append("};")
out.append("")

out.append("const NfcDecompEntry nfc_decomp_table[] = {")
for cp, off, ln in decomp_entries:
    out.append("    {0x%x, %d, %d}," % (cp, off, ln))
out.append("};")
out.append("const size_t nfc_decomp_table_len = %d;" % len(decomp_entries))
out.append("")

out.append("const NfcCombiningEntry nfc_combining_table[] = {")
for cp in sorted(combining):
    out.append("    {0x%x, %d}," % (cp, combining[cp]))
out.append("};")
out.append("const size_t nfc_combining_table_len = %d;" % len(combining))
out.append("")

out.append("const NfcComposeEntry nfc_compose_table[] = {")
for (cp1, cp2) in sorted(compose_pairs):
    out.append("    {0x%x, 0x%x, 0x%x}," % (cp1, cp2, compose_pairs[(cp1, cp2)]))
out.append("};")
out.append("const size_t nfc_compose_table_len = %d;" % len(compose_pairs))
out.append("")

sys.stdout.write('\n'.join(out) + '\n')

print("decomp entries: %d, combining entries: %d, compose pairs: %d, pool size: %d" % (
    len(decomp), len(combining), len(compose_pairs), len(pool)), file=sys.stderr)
