#!/usr/bin/env python3
# Generates adapters/go/nfc_tables.go: canonical-decomposition, combining-class,
# and canonical-composition data tables for a from-scratch Go NFC (Unicode
# Normalization Form C) implementation.
#
# Why this exists: Go's standard library has no Unicode normalization API
# (unlike Java's java.text.Normalizer, JS's String.prototype.normalize, or
# Rust's `unicode-normalization` crate used elsewhere in this project) and
# adding golang.org/x/text (a separate module, not part of the stdlib
# distribution) was ruled out to keep the adapter to stdlib-only per
# CONTRIBUTING.md. Ground truth for every table entry is Python's own
# unicodedata module (stdlib, Unicode 14.0.0) via unicodedata.normalize,
# which correctly accounts for the official canonical composition exclusion
# list without us needing to hand-transcribe it.
#
# Hangul syllables (and Hangul Jamo L/V/T composition) are excluded from the
# generated tables and handled algorithmically in Go instead (the standard
# arithmetic Hangul decomposition/composition rule), matching how every
# reference NFC implementation avoids a ~11172-entry Hangul table.
#
# Run: python3 adapters/go/scripts/gen_nfc_tables.py > adapters/go/nfc_tables.go

import unicodedata
import sys

SBase, LBase, VBase, TBase = 0xAC00, 0x1100, 0x1161, 0x11A7
LCount, VCount, TCount = 19, 21, 28
NCount = VCount * TCount
SCount = LCount * NCount


def is_hangul_syllable(cp):
    return SBase <= cp < SBase + SCount


decomp = {}       # rune -> full NFD string (differs from itself), non-Hangul
combining = {}     # rune -> combining class, only nonzero
compose_pairs = {}  # (cp1, cp2) -> composed rune, verified against Python's NFC

MAX_CP = 0x110000

for cp in range(MAX_CP):
    if is_hangul_syllable(cp):
        continue
    ch = chr(cp)
    ccc = unicodedata.combining(ch)
    if ccc != 0:
        combining[cp] = ccc
    nfd = unicodedata.normalize('NFD', ch)
    if nfd != ch:
        decomp[cp] = nfd

    # One-level canonical (non-compatibility) decomposition, for composition
    # pair candidates.
    raw = unicodedata.decomposition(ch)
    if not raw or raw.startswith('<'):
        continue
    parts = [int(x, 16) for x in raw.split(' ')]
    if len(parts) != 2:
        continue
    cp1, cp2 = parts
    if is_hangul_syllable(cp1) or is_hangul_syllable(cp2):
        continue
    if unicodedata.combining(chr(cp1)) != 0:
        continue  # starter-only composition rule
    test = unicodedata.normalize('NFC', chr(cp1) + chr(cp2))
    if len(test) == 1 and ord(test[0]) == cp:
        compose_pairs[(cp1, cp2)] = cp

out = []
out.append("// Code generated by adapters/go/scripts/gen_nfc_tables.py; DO NOT EDIT.")
out.append("// Ground truth: Python stdlib unicodedata, Unicode %s." % unicodedata.unidata_version)
out.append("package main")
out.append("")
out.append("// nfcDecomp maps a rune to its full canonical (NFD) decomposition string.")
out.append("// Hangul syllables are handled algorithmically, not via this table.")
out.append("var nfcDecomp = map[rune]string{")
for cp in sorted(decomp):
    s = decomp[cp]
    escaped = ''.join('\\u%04x' % ord(c) for c in s)
    out.append('\t0x%x: "%s",' % (cp, escaped))
out.append("}")
out.append("")
out.append("// nfcCombiningClass maps a rune to its Unicode canonical combining class")
out.append("// (only nonzero entries are present; absent runes have class 0).")
out.append("var nfcCombiningClass = map[rune]uint8{")
for cp in sorted(combining):
    out.append('\t0x%x: %d,' % (cp, combining[cp]))
out.append("}")
out.append("")
out.append("// nfcComposePairKey packs two runes into a single map key.")
out.append("type nfcComposePairKey struct{ a, b rune }")
out.append("")
out.append("// nfcCompose maps a (starter, combining-mark) pair to its precomposed rune,")
out.append("// restricted to pairs verified against Python's own NFC output so the")
out.append("// official composition-exclusion list is respected without transcribing it.")
out.append("// Hangul Jamo composition is handled algorithmically, not via this table.")
out.append("var nfcCompose = map[nfcComposePairKey]rune{")
for (cp1, cp2) in sorted(compose_pairs):
    out.append('\t{0x%x, 0x%x}: 0x%x,' % (cp1, cp2, compose_pairs[(cp1, cp2)]))
out.append("}")
out.append("")

sys.stdout.write('\n'.join(out) + '\n')

print("decomp entries: %d, combining entries: %d, compose pairs: %d" % (
    len(decomp), len(combining), len(compose_pairs)), file=sys.stderr)
