#ifndef ADAPTER_NFC_TABLES_H
#define ADAPTER_NFC_TABLES_H

/* Data tables backing nfc.c's hand-rolled Unicode NFC implementation.
 * Generated by scripts/gen_nfc_tables.py from Python's stdlib unicodedata
 * -- see nfc_tables.c's header comment. This header is hand-written and
 * stable; only nfc_tables.c is regenerated. */

#include <stddef.h>
#include <stdint.h>

typedef struct {
    uint32_t cp;
    uint32_t offset; /* index into nfc_decomp_pool */
    uint32_t len;    /* number of codepoints in the decomposition */
} NfcDecompEntry;

typedef struct {
    uint32_t cp;
    uint8_t ccc;
} NfcCombiningEntry;

typedef struct {
    uint32_t cp1;
    uint32_t cp2;
    uint32_t composed;
} NfcComposeEntry;

extern const uint32_t nfc_decomp_pool[];

extern const NfcDecompEntry nfc_decomp_table[];
extern const size_t nfc_decomp_table_len;

extern const NfcCombiningEntry nfc_combining_table[];
extern const size_t nfc_combining_table_len;

extern const NfcComposeEntry nfc_compose_table[];
extern const size_t nfc_compose_table_len;

#endif
